In [2]:
import numpy as np
list1 = [1, 2, 3, 4]
array1 = np.array(list1)
array1

array([1, 2, 3, 4])

In [3]:
import numpy as np
list2 = [[1, 2, 3], [4, 5, 6]]
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array3 = np.array([1, 2, 3, 4, 5])
array3

array([1, 2, 3, 4, 5])

In [5]:
array3 + 1

array([2, 3, 4, 5, 6])

In [6]:
array3 * 2

array([ 2,  4,  6,  8, 10])

In [7]:
array3 * array3

array([ 1,  4,  9, 16, 25])

In [8]:
list = np.arange(15).reshape((3, 5))
list

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
list.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [10]:
import pandas as pd
list = [1, 2, 3, 4, 5]
pd.Series(list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
s = pd.Series((list), index=["a", "b", "c", "d", "e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [13]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [14]:
s[["a", "c"]]

a    1
c    3
dtype: int64

In [15]:
m = {
    "liudehux": "handsome",
    "feifei": "graceful"
}
s2 = pd.Series(m)
s2

liudehux    handsome
feifei      graceful
dtype: object

In [16]:
dict = {
    "name": ["张大妈", "王大妈", "李大爷", "王大爷"],
    "sex": ["女", "女", "男", "男"],
    "age": [60, 77, 56, 88]
}
df = pd.DataFrame(dict)
df

name sex  age
0  张大妈   女   60
1  王大妈   女   77
2  李大爷   男   56
3  王大爷   男   88

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
name    4 non-null object
sex     4 non-null object
age     4 non-null int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes


In [18]:
df.name

0    张大妈
1    王大妈
2    李大爷
3    王大爷
Name: name, dtype: object

In [19]:
df["name"]

0    张大妈
1    王大妈
2    李大爷
3    王大爷
Name: name, dtype: object

In [21]:
df.iloc[0]

name    张大妈
sex       女
age      60
Name: 0, dtype: object

In [22]:
df.age = 76
df

name sex  age
0  张大妈   女   76
1  王大妈   女   76
2  李大爷   男   76
3  王大爷   男   76

In [23]:
df["age"] = [55, 56, 57, 88]
df

name sex  age
0  张大妈   女   55
1  王大妈   女   56
2  李大爷   男   57
3  王大爷   男   88

In [24]:
df["country"] = "China"
df

name sex  age country
0  张大妈   女   55   China
1  王大妈   女   56   China
2  李大爷   男   57   China
3  王大爷   男   88   China

In [25]:
df[["age", "name"]]

age name
0   55  张大妈
1   56  王大妈
2   57  李大爷
3   88  王大爷

In [26]:
df[df.age > 56]

name sex  age country
2  李大爷   男   57   China
3  王大爷   男   88   China

In [28]:
df[df.sex == "男"]

name sex  age country
2  李大爷   男   57   China
3  王大爷   男   88   China

In [30]:
(df.sex == "男") & (df.age > 60)

0    False
1    False
2    False
3     True
dtype: bool